# Generated by Django 3.2.11 on 2022-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_delete_group_member'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
