# Generated by Django 3.2.11 on 2022-01-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_name', models.CharField(max_length=100)),
                ('walk_length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('parking', models.BooleanField()),
                ('wheelchair_access', models.BooleanField()),
                ('toilet', models.BooleanField()),
                ('cafe', models.BooleanField()),
                ('rest_area', models.BooleanField()),
                ('scenic_spot', models.BooleanField()),
                ('dog_bin', models.BooleanField()),
                ('rating', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
