# Generated by Django 3.2.11 on 2022-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='step_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='walk',
            name='photo',
            field=models.ImageField(default=None, height_field=768, upload_to='', width_field=1024),
        ),
    ]
