# Generated by Django 3.2.12 on 2022-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_auto_20220201_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='photo',
        ),
        migrations.AlterField(
            model_name='walk',
            name='walk_length',
            field=models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=4),
        ),
    ]
