# Generated by Django 3.2.12 on 2022-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_auto_20220208_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='photo',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
