# Generated by Django 3.2.11 on 2022-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_walk_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='photo',
            field=models.ImageField(default='', upload_to='walks/photos/'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='rating',
            field=models.IntegerField(help_text='Rating out of 5'),
        ),
    ]
