# Generated by Django 3.2.11 on 2022-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0006_alter_walk_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=50.78448, max_digits=9),
        ),
        migrations.AddField(
            model_name='walk',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=-1.96783, max_digits=9),
        ),
    ]
