# Generated by Django 4.0.2 on 2022-02-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220214_1846'),
        ('reviews', '0005_auto_20220215_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.app_user'),
        ),
    ]
