# Generated by Django 4.0.2 on 2022-02-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='walk',
            new_name='walk_title',
        ),
    ]
