# Generated by Django 3.2.11 on 2022-02-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.TextField()),
                ('meeting_day', models.CharField(max_length=50)),
                ('meeting_time', models.DateTimeField()),
                ('meetup_link', models.CharField(max_length=300)),
            ],
        ),
    ]
