# Generated by Django 3.2.11 on 2022-02-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
