# Generated by Django 3.2.11 on 2022-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_photo',
            field=models.ImageField(default=None, height_field=768, upload_to='', width_field=1024),
        ),
    ]
