# Generated by Django 3.2.11 on 2022-02-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_group_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_Member',
        ),
    ]
