# Generated by Django 3.2.11 on 2022-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_group_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='meeting_time',
            field=models.CharField(default='Meeting times may vary, please check with group', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='meetup_link',
            field=models.CharField(help_text="Must include 'https://www.' ", max_length=300),
        ),
    ]
