# Generated by Django 4.0.2 on 2022-02-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_group_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='meetup_link',
            field=models.CharField(help_text="Must include 'https://www.' ", max_length=300),
        ),
    ]
