# Generated by Django 3.2.12 on 2022-02-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_meetup_link'),
        ('groups', '0006_auto_20220217_0640'),
    ]

    operations = [
    ]
